[2024-11-25T21:48:00.601+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: drift_detection_dag.detect_file manual__2024-11-25T21:47:51.266835+00:00 [queued]>
[2024-11-25T21:48:00.614+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: drift_detection_dag.detect_file manual__2024-11-25T21:47:51.266835+00:00 [queued]>
[2024-11-25T21:48:00.615+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-25T21:48:00.637+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonSensor): detect_file> on 2024-11-25 21:47:51.266835+00:00
[2024-11-25T21:48:00.649+0000] {standard_task_runner.py:57} INFO - Started process 567 to run task
[2024-11-25T21:48:00.653+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'drift_detection_dag', 'detect_file', 'manual__2024-11-25T21:47:51.266835+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/drift-detection.py', '--cfg-path', '/tmp/tmp1phtdhpq']
[2024-11-25T21:48:00.657+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask detect_file
[2024-11-25T21:48:00.728+0000] {task_command.py:416} INFO - Running <TaskInstance: drift_detection_dag.detect_file manual__2024-11-25T21:47:51.266835+00:00 [running]> on host 7f10b2294d44
[2024-11-25T21:48:00.820+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='drift_detection_dag' AIRFLOW_CTX_TASK_ID='detect_file' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T21:47:51.266835+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-25T21:47:51.266835+00:00'
[2024-11-25T21:48:00.822+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e1924700>
[2024-11-25T21:49:00.877+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e1924700>
[2024-11-25T21:50:00.926+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e1924700>
[2024-11-25T21:51:00.965+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e1924700>
[2024-11-25T21:52:01.016+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e1924700>
[2024-11-25T21:53:01.039+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e1924700>
[2024-11-25T21:54:01.096+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e1924700>
[2024-11-25T21:55:01.100+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e1924700>
[2024-11-25T21:56:01.152+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e1924700>
[2024-11-25T21:57:01.210+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e1924700>
[2024-11-25T21:58:01.268+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e1924700>
[2024-11-25T21:59:01.299+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e1924700>
[2024-11-25T22:00:01.354+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e1924700>
[2024-11-25T22:01:01.412+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e1924700>
[2024-11-25T22:02:01.470+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e1924700>
[2024-11-25T22:03:01.528+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e1924700>
[2024-11-25T22:04:00.728+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-11-25T22:04:00.731+0000] {process_utils.py:131} INFO - Sending 15 to group 567. PIDs of all processes in the group: [567]
[2024-11-25T22:04:00.732+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 567
[2024-11-25T22:04:00.732+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-25T22:04:00.745+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 285, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-11-25T22:04:00.750+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=drift_detection_dag, task_id=detect_file, execution_date=20241125T214751, start_date=20241125T214800, end_date=20241125T220400
[2024-11-25T22:04:00.766+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task detect_file (Task received SIGTERM signal; 567)
[2024-11-25T22:04:00.784+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=567, status='terminated', exitcode=1, started='21:48:00') (567) terminated with exit code 1
