[2024-11-25T21:51:47.106+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: drift_detection_dag.detect_file manual__2024-11-25T21:51:35.925335+00:00 [queued]>
[2024-11-25T21:51:47.122+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: drift_detection_dag.detect_file manual__2024-11-25T21:51:35.925335+00:00 [queued]>
[2024-11-25T21:51:47.124+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-25T21:51:47.149+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonSensor): detect_file> on 2024-11-25 21:51:35.925335+00:00
[2024-11-25T21:51:47.164+0000] {standard_task_runner.py:57} INFO - Started process 724 to run task
[2024-11-25T21:51:47.170+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'drift_detection_dag', 'detect_file', 'manual__2024-11-25T21:51:35.925335+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/drift-detection.py', '--cfg-path', '/tmp/tmp0qv5ysdc']
[2024-11-25T21:51:47.187+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask detect_file
[2024-11-25T21:51:47.314+0000] {task_command.py:416} INFO - Running <TaskInstance: drift_detection_dag.detect_file manual__2024-11-25T21:51:35.925335+00:00 [running]> on host 7f10b2294d44
[2024-11-25T21:51:47.525+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='drift_detection_dag' AIRFLOW_CTX_TASK_ID='detect_file' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T21:51:35.925335+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-25T21:51:35.925335+00:00'
[2024-11-25T21:51:47.528+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198f820>
[2024-11-25T21:52:47.582+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198f820>
[2024-11-25T21:53:47.638+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198f820>
[2024-11-25T21:54:47.695+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198f820>
[2024-11-25T21:55:47.753+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198f820>
[2024-11-25T21:56:47.814+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198f820>
[2024-11-25T21:57:47.870+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198f820>
[2024-11-25T21:58:47.927+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198f820>
[2024-11-25T21:59:47.985+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198f820>
[2024-11-25T22:00:48.043+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198f820>
[2024-11-25T22:01:48.101+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198f820>
[2024-11-25T22:02:48.159+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198f820>
[2024-11-25T22:03:24.333+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-11-25T22:03:24.344+0000] {process_utils.py:131} INFO - Sending 15 to group 724. PIDs of all processes in the group: [724]
[2024-11-25T22:03:24.345+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 724
[2024-11-25T22:03:24.346+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-25T22:03:24.364+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 285, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-11-25T22:03:24.373+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=drift_detection_dag, task_id=detect_file, execution_date=20241125T215135, start_date=20241125T215147, end_date=20241125T220324
[2024-11-25T22:03:24.399+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task detect_file (Task received SIGTERM signal; 724)
[2024-11-25T22:03:24.438+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=724, status='terminated', exitcode=1, started='21:51:46') (724) terminated with exit code 1
