[2024-11-25T23:53:27.994+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: drift_detection_dag.detect_file manual__2024-11-25T23:53:21.759937+00:00 [queued]>
[2024-11-25T23:53:28.021+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: drift_detection_dag.detect_file manual__2024-11-25T23:53:21.759937+00:00 [queued]>
[2024-11-25T23:53:28.022+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-25T23:53:28.046+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonSensor): detect_file> on 2024-11-25 23:53:21.759937+00:00
[2024-11-25T23:53:28.065+0000] {standard_task_runner.py:57} INFO - Started process 4040 to run task
[2024-11-25T23:53:28.076+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'drift_detection_dag', 'detect_file', 'manual__2024-11-25T23:53:21.759937+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/drift-detection.py', '--cfg-path', '/tmp/tmpgw6yufwo']
[2024-11-25T23:53:28.097+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask detect_file
[2024-11-25T23:53:28.244+0000] {task_command.py:416} INFO - Running <TaskInstance: drift_detection_dag.detect_file manual__2024-11-25T23:53:21.759937+00:00 [running]> on host 7f10b2294d44
[2024-11-25T23:53:28.558+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='drift_detection_dag' AIRFLOW_CTX_TASK_ID='detect_file' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T23:53:21.759937+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-25T23:53:21.759937+00:00'
[2024-11-25T23:53:28.566+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7f9fab26b790>
[2024-11-25T23:53:48.583+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7f9fab26b790>
[2024-11-25T23:54:08.603+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7f9fab26b790>
[2024-11-25T23:54:28.620+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7f9fab26b790>
[2024-11-25T23:54:28.621+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 274, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 60.05732054800319 seconds exceeds the specified timeout of 60.0.
[2024-11-25T23:54:28.635+0000] {taskinstance.py:1400} INFO - Immediate failure requested. Marking task as FAILED. dag_id=drift_detection_dag, task_id=detect_file, execution_date=20241125T235321, start_date=20241125T235328, end_date=20241125T235428
[2024-11-25T23:54:28.659+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 30 for task detect_file (Sensor has timed out; run duration of 60.05732054800319 seconds exceeds the specified timeout of 60.0.; 4040)
[2024-11-25T23:54:28.696+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-25T23:54:28.741+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
