[2024-11-25T21:50:11.002+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: drift_detection_dag.detect_file manual__2024-11-25T21:49:59.497873+00:00 [queued]>
[2024-11-25T21:50:11.016+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: drift_detection_dag.detect_file manual__2024-11-25T21:49:59.497873+00:00 [queued]>
[2024-11-25T21:50:11.016+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-25T21:50:11.034+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonSensor): detect_file> on 2024-11-25 21:49:59.497873+00:00
[2024-11-25T21:50:11.049+0000] {standard_task_runner.py:57} INFO - Started process 655 to run task
[2024-11-25T21:50:11.056+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'drift_detection_dag', 'detect_file', 'manual__2024-11-25T21:49:59.497873+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/drift-detection.py', '--cfg-path', '/tmp/tmps53e1u3t']
[2024-11-25T21:50:11.062+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask detect_file
[2024-11-25T21:50:11.188+0000] {task_command.py:416} INFO - Running <TaskInstance: drift_detection_dag.detect_file manual__2024-11-25T21:49:59.497873+00:00 [running]> on host 7f10b2294d44
[2024-11-25T21:50:11.295+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='drift_detection_dag' AIRFLOW_CTX_TASK_ID='detect_file' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T21:49:59.497873+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-25T21:49:59.497873+00:00'
[2024-11-25T21:50:11.297+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198e790>
[2024-11-25T21:51:11.353+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198e790>
[2024-11-25T21:52:11.382+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198e790>
[2024-11-25T21:53:11.438+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198e790>
[2024-11-25T21:54:11.486+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198e790>
[2024-11-25T21:55:11.546+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198e790>
[2024-11-25T21:56:11.602+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198e790>
[2024-11-25T21:57:11.660+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198e790>
[2024-11-25T21:58:11.719+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198e790>
[2024-11-25T21:59:11.727+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198e790>
[2024-11-25T22:00:11.783+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198e790>
[2024-11-25T22:01:11.842+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198e790>
[2024-11-25T22:02:11.900+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198e790>
[2024-11-25T22:03:11.957+0000] {python.py:72} INFO - Poking callable: <function _detect_file at 0x7fe7e198e790>
[2024-11-25T22:03:34.382+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-11-25T22:03:34.392+0000] {process_utils.py:131} INFO - Sending 15 to group 655. PIDs of all processes in the group: [655]
[2024-11-25T22:03:34.393+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 655
[2024-11-25T22:03:34.394+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-25T22:03:34.413+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 285, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-11-25T22:03:34.420+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=drift_detection_dag, task_id=detect_file, execution_date=20241125T214959, start_date=20241125T215011, end_date=20241125T220334
[2024-11-25T22:03:34.446+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task detect_file (Task received SIGTERM signal; 655)
[2024-11-25T22:03:34.486+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=655, status='terminated', exitcode=1, started='21:50:10') (655) terminated with exit code 1
